### ISSUE TITLE
cping reports packet loss if latency exceeds interval

### ISSUE THREAD

**Issue by nichols-356** [hSaria/cPing#2]
cPing is classifying high latency as packet loss if latency exceeds the interval time used in the cping command.

I had an issue with a service provider and was using cPing to do ad-hoc monitoring of the issue. Using the default interval of 1 second, cPing was reporting packet loss. Using the standard ping command with 1 second interval showed that latency was actually exceeding 1 second, but no packet loss was happening.

**workaround:** use the `-i` flag to increase interval above the observed latency.

**Comment by hSaria** [comment]
cPing v0.1.6 released which includes the fix (26f8d4211fbcde9120c0503db2ec13c76f699d3d) for this issue. Now, if a late-reply arrives, the respective result will be updated and marked with yellow.

Thanks a lot for your report!
