### ISSUE TITLE
Wired BUG, can not ping 114.114.114.114, other ok

### ISSUE THREAD

**Issue by xfzka** [hSaria/cPing#3]
### cPing version

0.1.8

### What's happening?

Cannot PING 114.114.114.114, Other like 8.8.8.8 1.1.1.1 OK

**Comment by xfzka** [comment]
<img width="869" alt="image" src="https://user-images.githubusercontent.com/24959175/175481210-624bd464-2b76-4fda-81db-2032bc03cc7d.png">
<img width="641" alt="image" src="https://user-images.githubusercontent.com/24959175/175481295-77f864bb-2368-47e2-b079-94695d419148.png">

**Comment by hSaria** [comment]
It works fine for me (ignore the packet loss; I'm on the other side of the Great Firewall).

<img width="845" alt="image" src="https://user-images.githubusercontent.com/34197532/175498677-f82cbc13-2a07-44a7-824b-e52808ca6984.png">

Would you mind:
1. Running `tcpdump -nw out.pcap icmp or udp port 53`
2. In a different window, run `cping 114.114.114.114` for a couple of seconds, then quit cPing
3. Run `ping 114.114.114.114` for a couple of seconds, then stop it
4. Stop `tcpdump` and attach `out.pcap` here

**Comment by hSaria** [comment]
Going to flag this as invalid for now. If you do run into such an issue again, please follow the steps above as I very much need that data to know what's happening.
